// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type Image struct {
	ID             string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ImageCreatedAt time.Time
}

type Tag struct {
	ID        int64
	Name      string
	ImageID   string
	CreatedAt time.Time
}
