// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
)

const createImage = `-- name: CreateImage :one
INSERT INTO images (id) VALUES (?) RETURNING id
`

func (q *Queries) CreateImage(ctx context.Context, id interface{}) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, createImage, id)
	err := row.Scan(&id)
	return id, err
}

const getImage = `-- name: GetImage :one
SELECT id FROM images WHERE id = ? LIMIT 1
`

func (q *Queries) GetImage(ctx context.Context, id interface{}) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getImage, id)
	err := row.Scan(&id)
	return id, err
}
